### ISSUE TITLE
Syntax Highlighting for namespace breaks when containing a dash '-'

### ISSUE THREAD

**Issue by TbLtzk** [chevdor/HyperledgerComposerSublimeText#11]
![image](https://user-images.githubusercontent.com/8383712/33073449-38c9b860-cec3-11e7-84e0-70ff4e9e98ee.png)

Seems that dash is an allowed character in the namespace (to be verified)

**Comment by chevdor** [comment]
Thanks for reporting, luckily on this one, the '-' is invalid so there is no issue.
`org.acme-corp.model` is **not** a valid namespace.
