### ISSUE TITLE
Unwanted highlight at relationship model

### ISSUE THREAD

**Issue by Cengkaruk** [chevdor/HyperledgerComposerSublimeText#2]
Hi @chevdor

Thanks for this plugin, a week ago there is no plugin for sublime.

I found small bug when model has a relationship. I wish i can help, but i have no idea about writing sublime plugin.

![screen shot 2017-10-21 at 9 16 53 pm](https://user-images.githubusercontent.com/629402/31852668-ea8bd10e-b6a5-11e7-91db-a05fc9b3c07f.png)

**Comment by chevdor** [comment]
Thank you for reporting and for your feedback. This is greatly appreciated.
The package is brand new indeed. Indeed I have seen that one. I need to fix
it.

You probably use 0.3.0. Check out the new version 0.7.0. It does not think
this issue I think but brings queries and acl.

**Comment by chevdor** [comment]
Check out the last version actually, I think it has been fixed. I no longer see the issue.
I close this one, but feel free to drop a comment if you spot the issue again.
